apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 003-istio-base
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: 'istio-base'
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: "1.18.7"
      helm:
        releaseName: "istio-base"
        ignoreMissingValueFiles: true
        valueFiles: []
  destination:
    namespace: 'istio-system'
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Big CRDs.