apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 008-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: 'gateway'
      repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: "1.18.7"
      helm:
        releaseName: "istio-ingressgateway"
        ignoreMissingValueFiles: true
        valueFiles: []
        values: |
          service:
            type: ClusterIP
          serviceAccount:
            name: istio-ingressgateway-service-account
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
  destination:
    namespace: 'istio-system'
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ServerSideApply=true  # Big CRDs.