apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 009-oidc-authservice
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: common/oidc-client/oidc-authservice/base
    repoURL: https://github.com/kubeflow/manifests
    targetRevision: 776d4f4
  destination:
    namespace: argo-cd
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ServerSideApply=true  # Big CRDs.
