apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/admission-webhook/upstream/overlays/cert-manager
    repoURL: https://github.com/kubeflow/manifests
    targetRevision: 776d4f4
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ServerSideApply=true  # Big CRDs.
