apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-dashboard
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/centraldashboard/upstream/overlays/kserve
    repoURL: https://github.com/kubeflow/manifests
    targetRevision: 776d4f4
    kustomize:
      patches:
      - target:
          kind: ConfigMap
          name: centraldashboard-config
        patch: |-
          - op: replace
            path: /data/links
            value: |
              {
                "menuLinks": [
                  {
                    "type": "item",
                    "link": "/jupyter/",
                    "text": "Notebooks",
                    "icon": "book"
                  },
                  {
                    "type": "item",
                    "link": "/volumes/",
                    "text": "Volumes",
                    "icon": "device:storage"
                  }
                ],
                "externalLinks": [ ],
                  "quickLinks": [
                    {
                      "text": "Create a new Notebook server",
                      "desc": "Notebook Servers",
                      "link": "/jupyter/new?namespace=kubeflow"
                    }
                  ],
                  "documentationItems": [
                    {
                      "text": "Getting Started with Kubeflow",
                      "desc": "Get your machine-learning workflow up and running on Kubeflow",
                      "link": "https://www.kubeflow.org/docs/started/getting-started/"
                    }
                  ]
              }
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - ServerSideApply=true  # Big CRDs.
