---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-kf-core-kubeflow-namespace
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                namespace: kubeflow
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values: {}
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values: {}
  template:
    metadata:
      name: addon-{{name}}-kf-core-kubeflow-namespace
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        path: common/kubeflow-namespace/base
        repoURL: https://github.com/kubeflow/manifests
        targetRevision: 776d4f4
      destination:
        namespace: '{{values.namespace}}'
        name: '{{name}}'
      syncPolicy:
#        automated:
#          prune: false
        syncOptions:
          - ServerSideApply=true  # Big CRDs.
