---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-kf-istio-base
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                namespace: istio-system
                addonChart: base
                # anything not staging or prod use this version
                addonChartVersion: "1.18.7"
                addonChartRepository: "https://istio-release.storage.googleapis.com/charts"
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values: {}
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values: {}
  template:
    metadata:
      name: addon-{{name}}-kf-istio-base
      annotations:
        argocd.argoproj.io/sync-wave: "-20"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        # - repoURL: '{{metadata.annotations.addons_repo_url}}'
        #   targetRevision: '{{metadata.annotations.addons_repo_revision}}'
        #   ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles: []
            values: ""
      destination:
        namespace: '{{values.namespace}}'
        name: '{{name}}'
      syncPolicy:
       automated:
         prune: false
        syncOptions:
          - ServerSideApply=true  # Big CRDs.
          - CreateNamespace=true
